---

- name : Configure Zabbix Agent
  template:
    src: templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: zabbix
    mode: 0640
  notify: restart zabbix-agent

