---
- name: Configure Zabbix official repository
  yum_repository:
    name: Zabbix.repo
    description: Zabbix Official Repository
    baseurl: http://repo.zabbix.com/zabbix/3.0/rhel/7/$basearch
    gpgkey: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    gpgcheck: yes
- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - unixODBC
    - libtool-ltdl
    - zabbix-agent 
