---
- name: Configure Zabbix official repository
  yum_repository:
    name: Zabbix
    description: Zabbix Official Repository
    baseurl: http://repo.zabbix.com/zabbix/4.0/rhel/7/$basearch
    gpgkey: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
    gpgcheck: yes
    priority: 2

- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-agent
